#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 65536
#define ONCHIP_MEMORY2_0_END 0xffff
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'pio_a', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_A_'.
 * The prefix is the slave descriptor.
 */
#define PIO_A_COMPONENT_TYPE altera_avalon_pio
#define PIO_A_COMPONENT_NAME pio_a
#define PIO_A_BASE 0x0
#define PIO_A_SPAN 16
#define PIO_A_END 0xf
#define PIO_A_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_A_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_A_CAPTURE 0
#define PIO_A_DATA_WIDTH 32
#define PIO_A_DO_TEST_BENCH_WIRING 0
#define PIO_A_DRIVEN_SIM_VALUE 0
#define PIO_A_EDGE_TYPE NONE
#define PIO_A_FREQ 50000000
#define PIO_A_HAS_IN 0
#define PIO_A_HAS_OUT 1
#define PIO_A_HAS_TRI 0
#define PIO_A_IRQ_TYPE NONE
#define PIO_A_RESET_VALUE 0

/*
 * Macros for device 'pio_b', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_B_'.
 * The prefix is the slave descriptor.
 */
#define PIO_B_COMPONENT_TYPE altera_avalon_pio
#define PIO_B_COMPONENT_NAME pio_b
#define PIO_B_BASE 0x10
#define PIO_B_SPAN 16
#define PIO_B_END 0x1f
#define PIO_B_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_B_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_B_CAPTURE 0
#define PIO_B_DATA_WIDTH 32
#define PIO_B_DO_TEST_BENCH_WIRING 0
#define PIO_B_DRIVEN_SIM_VALUE 0
#define PIO_B_EDGE_TYPE NONE
#define PIO_B_FREQ 50000000
#define PIO_B_HAS_IN 0
#define PIO_B_HAS_OUT 1
#define PIO_B_HAS_TRI 0
#define PIO_B_IRQ_TYPE NONE
#define PIO_B_RESET_VALUE 0

/*
 * Macros for device 'pio_sum', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_SUM_'.
 * The prefix is the slave descriptor.
 */
#define PIO_SUM_COMPONENT_TYPE altera_avalon_pio
#define PIO_SUM_COMPONENT_NAME pio_sum
#define PIO_SUM_BASE 0x20
#define PIO_SUM_SPAN 16
#define PIO_SUM_END 0x2f
#define PIO_SUM_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_SUM_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_SUM_CAPTURE 0
#define PIO_SUM_DATA_WIDTH 32
#define PIO_SUM_DO_TEST_BENCH_WIRING 0
#define PIO_SUM_DRIVEN_SIM_VALUE 0
#define PIO_SUM_EDGE_TYPE NONE
#define PIO_SUM_FREQ 50000000
#define PIO_SUM_HAS_IN 1
#define PIO_SUM_HAS_OUT 0
#define PIO_SUM_HAS_TRI 0
#define PIO_SUM_IRQ_TYPE NONE
#define PIO_SUM_RESET_VALUE 0

/*
 * Macros for device 'pio_prod', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_PROD_'.
 * The prefix is the slave descriptor.
 */
#define PIO_PROD_COMPONENT_TYPE altera_avalon_pio
#define PIO_PROD_COMPONENT_NAME pio_prod
#define PIO_PROD_BASE 0x30
#define PIO_PROD_SPAN 16
#define PIO_PROD_END 0x3f
#define PIO_PROD_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_PROD_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_PROD_CAPTURE 0
#define PIO_PROD_DATA_WIDTH 32
#define PIO_PROD_DO_TEST_BENCH_WIRING 0
#define PIO_PROD_DRIVEN_SIM_VALUE 0
#define PIO_PROD_EDGE_TYPE NONE
#define PIO_PROD_FREQ 50000000
#define PIO_PROD_HAS_IN 1
#define PIO_PROD_HAS_OUT 0
#define PIO_PROD_HAS_TRI 0
#define PIO_PROD_IRQ_TYPE NONE
#define PIO_PROD_RESET_VALUE 0

/*
 * Macros for device 'clk_24', class 'altera_avalon_pio'
 * The macros are prefixed with 'CLK_24_'.
 * The prefix is the slave descriptor.
 */
#define CLK_24_COMPONENT_TYPE altera_avalon_pio
#define CLK_24_COMPONENT_NAME clk_24
#define CLK_24_BASE 0x40
#define CLK_24_SPAN 16
#define CLK_24_END 0x4f
#define CLK_24_BIT_CLEARING_EDGE_REGISTER 0
#define CLK_24_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CLK_24_CAPTURE 0
#define CLK_24_DATA_WIDTH 24
#define CLK_24_DO_TEST_BENCH_WIRING 0
#define CLK_24_DRIVEN_SIM_VALUE 0
#define CLK_24_EDGE_TYPE NONE
#define CLK_24_FREQ 50000000
#define CLK_24_HAS_IN 1
#define CLK_24_HAS_OUT 0
#define CLK_24_HAS_TRI 0
#define CLK_24_IRQ_TYPE NONE
#define CLK_24_RESET_VALUE 0

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1601056072

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x20007
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


#endif /* _ALTERA_HPS_0_H_ */
